name: cryptoadv
description: CryptYRM - Application de cryptographie et sécurité.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.7 <4.0.0'
  flutter: '>=3.38.4'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Base de données — hive (mobile, desktop, web / IndexedDB)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Crypto
  crypto: ^3.0.7
  cryptography: ^2.9.0
  pointycastle: ^3.9.1

  # UI & Utils
  cupertino_icons: ^1.0.9
  provider: ^6.1.5+1
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2
  file_picker: ^8.3.7
  path_provider: ^2.1.5

  # Audio (Messages vocaux)
  record: ^6.2.0
  audioplayers: ^5.2.1

  # Réseau — EC2 backend
  http: ^1.2.1
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
