// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpRmEdfduy4nTJW-YUdAxDx3TKU-6ax14',
    appId: '1:839630076882:web:c719fac8284a820aa5a60b',
    messagingSenderId: '839630076882',
    projectId: 'cryptyrm',
    authDomain: 'cryptyrm.firebaseapp.com',
    storageBucket: 'cryptyrm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe62STNYpHBqpyYaoo5lfzQ4Mfe1jBpOs',
    appId: '1:839630076882:android:e44d7a8f71855c0aa5a60b',
    messagingSenderId: '839630076882',
    projectId: 'cryptyrm',
    storageBucket: 'cryptyrm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTI7zZ-1UQNEpDuTICvBslC8s1cME32HU',
    appId: '1:839630076882:ios:eae86a6a4f282017a5a60b',
    messagingSenderId: '839630076882',
    projectId: 'cryptyrm',
    storageBucket: 'cryptyrm.firebasestorage.app',
    iosBundleId: 'com.example.cryptoadv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTI7zZ-1UQNEpDuTICvBslC8s1cME32HU',
    appId: '1:839630076882:ios:eae86a6a4f282017a5a60b',
    messagingSenderId: '839630076882',
    projectId: 'cryptyrm',
    storageBucket: 'cryptyrm.firebasestorage.app',
    iosBundleId: 'com.example.cryptoadv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpRmEdfduy4nTJW-YUdAxDx3TKU-6ax14',
    appId: '1:839630076882:web:df6835158cfc26a3a5a60b',
    messagingSenderId: '839630076882',
    projectId: 'cryptyrm',
    authDomain: 'cryptyrm.firebaseapp.com',
    storageBucket: 'cryptyrm.firebasestorage.app',
  );
}
